import { ArrowRight, Check, Factory, MapPin, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import Seo from "@/components/Seo";
import SectionHeading from "@/components/SectionHeading";
import { brand, gallery, productImages } from "@/lib/siteData";

export default function About() {
  return (
    <>
      <Seo title="About Us | Kharbanda Saw Dust Store - Trusted Since 1974" description="Discover Kharbanda Saw Dust Store, a family-owned wood dust processing and nationwide B2B supply business with roots in Delhi and Yamuna Nagar since 1974." />
      <section className="page-hero" data-testid="about-hero"><div className="mx-auto max-w-7xl px-5 lg:px-8"><p className="section-eyebrow text-[#D7A16F]" data-testid="about-eyebrow">About Kharbanda</p><h1 className="mt-4 max-w-4xl font-heading text-4xl font-bold tracking-[-0.06em] text-white sm:text-6xl" data-testid="about-heading">Where wood finds purpose: our B2B legacy since 1974.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/70" data-testid="about-hero-description">A family-owned wood dust processing, manufacturing and supply business for buyers who value clear conversations, reliable service and practical material solutions.</p></div></section>
      <section className="section-shell" data-testid="about-story-section"><div className="grid items-center gap-12 lg:grid-cols-[1fr_1fr]"><div><SectionHeading eyebrow="Our business" title="Experience that stays close to the material." body="Kharbanda Saw Dust Store has grown from a family business started by Mr. Radha Kishan Kharbanda into a second-generation B2B supplier serving customers across India. We work with different wood species and qualities across saw dust, wood powder, wood shavings and wooden flakes." /><p className="mt-5 text-base leading-7 text-[#57534E]" data-testid="about-story-copy">Our Delhi office and Yamuna Nagar factory support a simple approach: understand the buyer’s intended application, discuss the relevant material requirements and work toward a dependable supply conversation.</p><Link to="/our-legacy" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-[#183A2B] underline decoration-[#C68B59] decoration-2 underline-offset-4" data-testid="about-legacy-link">Meet our inspiration <ArrowRight className="size-4" aria-hidden="true" /></Link></div><div className="relative"><img src={productImages.factory} alt="Industrial wood processing machinery in a factory environment" className="aspect-[1.1/1] w-full object-cover" data-testid="about-factory-image" /><div className="absolute bottom-5 left-5 max-w-[15rem] bg-[#183A2B] p-5 text-white"><Factory className="size-5 text-[#D7A16F]" aria-hidden="true" /><p className="mt-3 text-sm leading-6" data-testid="about-factory-caption">A practical base for wood material processing and supply conversations.</p></div></div></div></section>
      <section className="section-shell border-y border-[#E0D7C6] bg-white" data-testid="about-values-section"><SectionHeading eyebrow="What guides us" title="Quality, reliability and service." body="The promise is straightforward: take every requirement seriously and keep the conversation grounded in the buyer’s use case." /><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{["Quality you can trust", "Reliable suppliers nationwide", "Committed to service & satisfaction", "Application-focused solutions"].map((value, index) => <div className="border-t-2 border-[#2D6A4F] pt-5" key={value} data-testid={`about-value-${index}`}><Check className="size-5 text-[#2D6A4F]" aria-hidden="true" /><h3 className="mt-5 font-heading text-xl font-bold" data-testid={`about-value-heading-${index}`}>{value}</h3><p className="mt-3 text-sm leading-6 text-[#57534E]" data-testid={`about-value-copy-${index}`}>A clear part of how we work with manufacturers, procurement teams and distributors.</p></div>)}</div></section>
      <section id="gallery" className="section-shell" data-testid="gallery-section"><div className="flex items-end justify-between gap-5"><SectionHeading eyebrow="Gallery" title="The work, the material, the brand." body="Our provided Kharbanda photographs are shown here as a record of the products and stock environment." /></div><div className="mt-10 grid grid-cols-2 gap-3 md:grid-cols-3">{gallery.map((item, index) => <figure key={item.label} className={`${index === 0 ? "md:col-span-2 md:row-span-2" : ""} overflow-hidden bg-[#F4EFE6]`}><img src={item.image} alt={item.alt} loading="lazy" className="aspect-square size-full object-cover transition duration-500 hover:scale-105 md:aspect-auto md:min-h-52" data-testid={`gallery-image-${index}`} /><figcaption className="sr-only" data-testid={`gallery-caption-${index}`}>{item.label}</figcaption></figure>)}</div></section>
      <section className="section-shell bg-[#F4EFE6]" data-testid="about-locations-section"><div className="grid gap-10 lg:grid-cols-[0.7fr_1.3fr]"><SectionHeading eyebrow="Locations" title="Rooted in Delhi. Connected to India." body="Visit or contact us through the location that works for your business conversation." /><div className="grid gap-5 sm:grid-cols-2"><div className="border border-[#E0D7C6] bg-[#FBF9F5] p-6" data-testid="about-office-card"><MapPin className="size-5 text-[#2D6A4F]" aria-hidden="true" /><h3 className="mt-5 font-heading text-xl font-bold" data-testid="about-office-heading">Delhi Office</h3><p className="mt-2 text-sm leading-6 text-[#57534E]" data-testid="about-office-address">{brand.office}</p></div><div className="border border-[#E0D7C6] bg-[#FBF9F5] p-6" data-testid="about-factory-card"><Factory className="size-5 text-[#2D6A4F]" aria-hidden="true" /><h3 className="mt-5 font-heading text-xl font-bold" data-testid="about-factory-heading">Yamuna Nagar Factory</h3><p className="mt-2 text-sm leading-6 text-[#57534E]" data-testid="about-factory-address">{brand.factory}</p></div></div></div></section>
      <section className="cta-band" data-testid="about-cta"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-6 px-5 sm:flex-row sm:items-center lg:px-8"><div><ShieldCheck className="size-6 text-[#D7A16F]" aria-hidden="true" /><h2 className="mt-3 font-heading text-3xl font-bold text-white" data-testid="about-cta-heading">Talk to our team about your requirement.</h2></div><Link to="/contact" className="inline-flex items-center gap-2 rounded-full bg-[#D7A16F] px-5 py-3 text-sm font-bold text-[#2C190D]" data-testid="about-cta-button">Request a bulk quote <ArrowRight className="size-4" aria-hidden="true" /></Link></div></section>
    </>
  );
}