import { ArrowRight, BookOpen, Clock3 } from "lucide-react";
import { Link } from "react-router-dom";
import Seo from "@/components/Seo";
import SectionHeading from "@/components/SectionHeading";
import { brand, productImages } from "@/lib/siteData";

const futureArticles = ["How to Choose a Sawdust Supplier for Industrial Applications", "Sawdust vs Wood Powder: What’s the Difference?", "How Sawdust Is Used for Briquette Manufacturing", "Understanding Wood Shavings and Wooden Flakes", "Choosing Wood Species for Different Industrial Applications", "Bulk Sawdust Buying Guide for Businesses"];

export default function Blog() {
  return (
    <>
      <Seo title="Wood Processing & Industrial Sawdust Insights | Buyer Guide" description="Useful, practical articles about sawdust, wood powder, wood shavings, wooden flakes, biomass, briquettes and choosing a bulk wood material supplier." />
      <section className="page-hero" data-testid="blog-hero"><div className="mx-auto max-w-7xl px-5 lg:px-8"><p className="section-eyebrow font-bold text-white" data-testid="blog-eyebrow">Knowledge hub</p><h1 className="mt-4 max-w-4xl font-heading text-4xl font-bold tracking-[-0.06em] text-white sm:text-6xl" data-testid="blog-heading">Industrial sawdust &amp; wood fiber insights.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/70" data-testid="blog-description">A practical starting point for buyers, manufacturers and procurement teams exploring wood-based materials.</p></div></section>
      <section className="section-shell" data-testid="blog-featured-section"><div className="grid overflow-hidden border border-[#E0D7C6] bg-white lg:grid-cols-[0.85fr_1.15fr]"><img src={productImages.powder} alt="Fine saw dust powder close-up for an industrial material guide" className="h-full min-h-72 w-full object-cover" data-testid="blog-featured-image" /><article className="p-7 sm:p-10"><div className="flex flex-wrap items-center gap-4 text-xs font-bold uppercase tracking-[0.15em] text-[#2D6A4F]"><span className="inline-flex items-center gap-2" data-testid="blog-featured-type"><BookOpen className="size-4" aria-hidden="true" /> Buyer guide</span><span className="inline-flex items-center gap-2" data-testid="blog-featured-time"><Clock3 className="size-4" aria-hidden="true" /> 6 min read</span></div><h2 className="mt-6 font-heading text-3xl font-bold tracking-[-0.04em] sm:text-4xl" data-testid="blog-article-heading">What Is Sawdust? A Basic Guide to Wood Dust and Its Industrial Uses</h2><p className="mt-5 text-base leading-7 text-[#57534E]" data-testid="blog-article-intro">Sawdust is the small wood material created when timber is cut, sawn, drilled or processed. For a buyer, the useful question is not only what sawdust is, but whether its wood species, particle character and quality suit the intended application.</p></article></div></section>
      <article id="what-is-sawdust" className="section-shell border-y border-[#E0D7C6] bg-[#F4EFE6]" data-testid="blog-article-content"><div className="mx-auto max-w-3xl"><p className="section-eyebrow" data-testid="article-eyebrow">The basics</p><h2 className="mt-3 font-heading text-3xl font-bold tracking-[-0.04em]" data-testid="article-title">What is sawdust, and why does it matter?</h2><div className="prose-copy mt-8"><h3 data-testid="article-subheading-definition">Sawdust in simple terms</h3><p data-testid="article-paragraph-definition">Sawdust is the small wood particle produced during timber processing. It can vary because wood species, the cutting process and the way material is handled all affect the finished material.</p><h3 data-testid="article-subheading-differences">Sawdust, wood powder, shavings and flakes</h3><p data-testid="article-paragraph-differences">Sawdust generally describes smaller particles created during sawing. Wood powder is finer; wood shavings are lighter, curled pieces; and wooden flakes are larger, flatter particles. These are useful distinctions when a buyer is describing an application to a supplier.</p><h3 data-testid="article-subheading-applications">Common industrial uses</h3><p data-testid="article-paragraph-applications">Depending on the material requirements, wood-based products may be discussed for briquettes and biomass, mushroom cultivation, animal bedding, composites, flooring, mosquito coil manufacturing, Bakelite, petroleum-related absorption and other industrial applications.</p><h3 data-testid="article-subheading-buyers">How businesses should choose a supplier</h3><p data-testid="article-paragraph-buyers">Start with the intended application, required quantity, delivery location, preferred wood species or quality and any process-specific expectations. A clear brief helps a bulk sawdust supplier understand whether sawdust, wood powder, shavings or flakes should be discussed.</p></div><Link to="/contact" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-[#183A2B] underline decoration-[#C68B59] decoration-2 underline-offset-4" data-testid="article-contact-link">Discuss your material requirement <ArrowRight className="size-4" aria-hidden="true" /></Link></div></article>
      <section className="section-shell" data-testid="blog-coming-soon-section"><SectionHeading eyebrow="More to come" title="Practical articles for future buying decisions." body="This knowledge hub is structured so useful product, application and location articles can be added over time." /><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{futureArticles.map((article, index) => <div key={article} className="border border-[#E0D7C6] bg-white p-5" data-testid={`future-article-${index}`}><span className="text-xs font-bold uppercase tracking-[0.15em] text-[#C68B59]">Coming soon</span><h3 className="mt-4 font-heading text-xl font-bold" data-testid={`future-article-title-${index}`}>{article}</h3><p className="mt-3 text-sm leading-6 text-[#57534E]" data-testid={`future-article-copy-${index}`}>A planned buyer-focused article from {brand.name}.</p></div>)}</div></section>
    </>
  );
}