import { Leaf, Users } from "lucide-react";
import Seo from "@/components/Seo";
import SectionHeading from "@/components/SectionHeading";
import { brand } from "@/lib/siteData";

export default function Legacy() {
  return (
    <>
      <Seo title="Our Legacy | Kharbanda Saw Dust Store - Trusted Since 1974" description="Learn how Mr. Radha Kishan Kharbanda started the business in 1974 and how Mr. Ashok Kumar Kharbanda carries the second-generation wood supply business forward." />
      <section className="page-hero" data-testid="legacy-page-hero"><div className="mx-auto max-w-7xl px-5 lg:px-8"><p className="section-eyebrow text-white" data-testid="legacy-page-eyebrow">Our inspiration</p><h1 className="mt-4 max-w-4xl font-heading text-4xl font-bold tracking-[-0.06em] text-white sm:text-6xl" data-testid="legacy-page-heading">Five decades of industrial excellence in wood processing.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/70" data-testid="legacy-page-description">Two Generations. One Commitment. A family story shaped by material knowledge, long-term customer relationships and a steady focus on service.</p></div></section>
      <section className="section-shell" data-testid="legacy-timeline-section"><div className="grid gap-12 lg:grid-cols-[0.75fr_1.25fr]"><div className="lg:sticky lg:top-32 lg:self-start"><SectionHeading eyebrow="The people behind the name" title="A business passed forward with care." /></div><div className="relative border-l border-[#C68B59] pl-8 sm:pl-12"><div className="timeline-node" aria-hidden="true" /><article className="pb-16" data-testid="legacy-1974-entry"><p className="text-sm font-bold uppercase tracking-[0.2em] text-[#2D6A4F]" data-testid="legacy-1974-year">1974</p><h2 className="mt-3 font-heading text-3xl font-bold tracking-[-0.04em]" data-testid="legacy-1974-heading">Founded by {brand.founder}</h2><p className="mt-4 max-w-xl text-base leading-7 text-[#57534E]" data-testid="legacy-1974-copy">Mr. Radha Kishan Kharbanda started the business with a focus on wood processing, quality, reliability and serving industrial customers. The foundation was built on understanding wood as a useful material — not simply as waste.</p></article><div className="timeline-node" aria-hidden="true" /><article data-testid="legacy-present-entry"><p className="text-sm font-bold uppercase tracking-[0.2em] text-[#2D6A4F]" data-testid="legacy-present-label">Present day</p><h2 className="mt-3 font-heading text-3xl font-bold tracking-[-0.04em]" data-testid="legacy-present-heading">Second generation, same commitment.</h2><p className="mt-4 max-w-xl text-base leading-7 text-[#57534E]" data-testid="legacy-present-copy">Today, the business is handled by {brand.currentGeneration}, son of {brand.founder}. He carries forward the family’s experience while serving modern industrial requirements across India.</p><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="depth-surface border border-[#E0D7C6] p-5" data-testid="legacy-knowledge-card"><Leaf className="size-5 text-[#2D6A4F]" aria-hidden="true" /><h3 className="mt-4 font-heading text-lg font-bold" data-testid="legacy-knowledge-heading">Generational knowledge</h3><p className="mt-2 text-sm leading-6 text-[#57534E]" data-testid="legacy-knowledge-copy">Understanding wood materials, species, qualities and the needs of industrial buyers.</p></div><div className="depth-surface border border-[#E0D7C6] p-5" data-testid="legacy-relationships-card"><Users className="size-5 text-[#2D6A4F]" aria-hidden="true" /><h3 className="mt-4 font-heading text-lg font-bold" data-testid="legacy-relationships-heading">Long-term relationships</h3><p className="mt-2 text-sm leading-6 text-[#57534E]" data-testid="legacy-relationships-copy">A service mindset built around clear requirements and customer satisfaction.</p></div></div></article></div></div></section>
    </>
  );
}