import { ArrowRight, Check, MessageCircle } from "lucide-react";
import { Link } from "react-router-dom";
import Seo from "@/components/Seo";
import SectionHeading from "@/components/SectionHeading";
import ProductCard from "@/components/ProductCard";
import { brand, products, whatsappUrl } from "@/lib/siteData";

export default function Products() {
  return (
    <>
      <Seo title="Industrial Wood Products | Saw Dust, Wood Powder, Flakes & Shavings" description="Explore saw dust, wood powder, wood shavings and wooden flakes from an industrial supplier serving Delhi, Yamuna Nagar and buyers across India." />
      <section className="page-hero" data-testid="products-hero"><div className="mx-auto max-w-7xl px-5 lg:px-8"><p className="section-eyebrow text-white" data-testid="products-eyebrow">Our product range</p><h1 className="mt-4 max-w-4xl font-heading text-4xl font-bold tracking-[-0.06em] text-white sm:text-6xl" data-testid="products-heading">Premium industrial wood dust &amp; fiber products.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/70" data-testid="products-description">Saw dust, wood powder, wood shavings and wooden flakes for businesses that need a dependable supply conversation.</p></div></section>
      <section className="section-shell" data-testid="products-intro-section"><div className="flex flex-col justify-between gap-7 sm:flex-row sm:items-end"><SectionHeading eyebrow="For real requirements" title="Choose a material. Then discuss the details." body="We deal in different wood species and qualities. Specifications can be discussed according to application and buyer requirements; exact technical specifications are not assumed on this page." /><Link to="/contact" className="inline-flex shrink-0 items-center gap-2 rounded-full bg-[#183A2B] px-5 py-3 text-sm font-bold text-white" data-testid="products-quote-button">Request a Quote <ArrowRight className="size-4" aria-hidden="true" /></Link></div><div className="mt-12 grid gap-6 md:grid-cols-2">{products.map((product) => <ProductCard key={product.id} product={product} />)}</div></section>
      <section className="section-shell border-y border-[#E0D7C6] bg-[#F4EFE6]" data-testid="products-fit-section"><div className="grid gap-10 lg:grid-cols-[0.75fr_1.25fr]"><SectionHeading eyebrow="Before you buy" title="A better quote starts with context." body="Share the material you are considering, your application, location and required quantity. Our team can then understand the conversation more clearly." /><div className="grid gap-4 sm:grid-cols-2">{["Intended application", "Wood species or quality", "Required quantity", "Delivery location"].map((item, index) => <div key={item} className="flex gap-4 border border-[#E0D7C6] bg-[#FBF9F5] p-5" data-testid={`products-fit-item-${index}`}><span className="font-heading text-2xl font-bold text-[#C68B59]">0{index + 1}</span><div><h3 className="font-heading text-lg font-bold" data-testid={`products-fit-heading-${index}`}>{item}</h3><p className="mt-2 text-sm leading-6 text-[#57534E]" data-testid={`products-fit-copy-${index}`}>Helpful context for a more useful industrial discussion.</p></div></div>)}</div></div></section>
      <section className="section-shell" data-testid="products-seo-section"><div className="grid items-center gap-10 md:grid-cols-2"><div><p className="section-eyebrow" data-testid="products-seo-eyebrow">Wood dust supplier India</p><h2 className="mt-3 font-heading text-3xl font-bold tracking-[-0.04em]" data-testid="products-seo-heading">Material supply with a practical, nationwide outlook.</h2><p className="mt-4 text-base leading-7 text-[#57534E]" data-testid="products-seo-copy">Whether you are looking for a sawdust supplier Delhi, a wood powder supplier or sawdust wholesale for an industrial process, start with the requirement. We serve customers across India from our Delhi and Yamuna Nagar locations.</p><div className="mt-6 grid gap-3">{["Hardwood sawdust supplier conversations", "Sawdust for briquettes and biomass", "Wood shavings and flakes in volume", "Application-led product discussions"].map((item) => <p key={item} className="flex items-center gap-2 text-sm font-semibold text-[#3D2314]" data-testid={`products-seo-point-${item.toLowerCase().replaceAll(" ", "-")}`}><Check className="size-4 text-[#2D6A4F]" aria-hidden="true" />{item}</p>)}</div></div><div className="border border-[#E0D7C6] bg-[#183A2B] p-8 text-white"><MessageCircle className="size-7 text-[#D7A16F]" aria-hidden="true" /><h2 className="mt-6 font-heading text-2xl font-bold" data-testid="products-whatsapp-heading">Want to discuss your grade or quantity?</h2><p className="mt-3 text-sm leading-6 text-white/70" data-testid="products-whatsapp-copy">Send an enquiry with the material, intended use and delivery location. We will take it from there.</p><a href={whatsappUrl("Hello Kharbanda Saw Dust Store, I would like to discuss a product requirement.")} target="_blank" rel="noopener noreferrer" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#25D366] px-5 py-3 text-sm font-bold text-[#082714]" data-testid="products-whatsapp-button">WhatsApp the team <ArrowRight className="size-4" aria-hidden="true" /></a></div></div></section>
      <p className="sr-only" data-testid="products-business-name">{brand.name}</p>
    </>
  );
}